AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Redshift Data API Lambda example"
        Parameters:
          - RedshiftSecretArn

    ParameterLabels:
      RedshiftSecretArn:
        default: "Secret Mager ARN for RS cluster"

Parameters:
  RedshiftSecretArn:
    Type: String
    Description: 'Enter the ARN of the secret containing the user and password fot the RS cluster'
    MinLength: 20
    MaxLength: 2048

Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.example.myapp.App::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: ./target/myapp.jar
      # Attach policies here to give the function permission to access other AWS resources if needed
      # See: https://github.com/awslabs/serverless-application-model/blob/master/docs/policy_templates.rst
      # eg:
      Policies:
       - AmazonRedshiftDataFullAccess
      Environment:
        Variables:
          RS_SECRET_ARN: !Ref RedshiftSecretArn
